### ISSUE TITLE
500 Server Error

### ISSUE THREAD

**Issue by heganiklas** [franksmule/prestashop-stripejs#21]
I have successfully installed and configured the module on Prestashop 1.6.0.11. I have also entered my Stripe keys and other info and managed to make successful test payments. But... As soon as I set the module to "Live" (and doing the same in the Stripe Dashboard), I get the following error:

500 Server Error
Oops, something went wrong.

Try to refresh this page or feel free to contact us if the problem persists.

The annoying thing is that the payment is actually accepted....

Any thoughts? Thanks a lot in advance!

Best,

Niklas

![screen shot 2015-02-04 at 12 48 05](https://cloud.githubusercontent.com/assets/10848196/6040258/0a283a0e-ac70-11e4-8334-d83204a913ae.png)

**Comment by NadjibBELLOUNDJA** [comment]
Hi heganiklas,

Did you manage to make it work? I have the same issue and could not resolve it so far. Any extra info would be great.

Many thanks.

**Comment by ryanteck** [comment]
Hi,

I've been moving from squarespace to hosting my own again and have been testing the stripe module.

No errors at all in test mode nor in live mode (when processing a £1 test transaction) and didn't have issues with neither.

I'm using latest prestashop version, 2015-04-07 stripe API and the 5 page checkout sequence.

My PHP error log does show there are warnings on lines 521 and 571. I'm going to guess that the lines change with an inclusion of something or a change as the line on 571 doesn't seem like it should produce this warning but 521 does.


I'd guess your error logs would say what causes the issues.

**Comment by trevorgilligan** [comment]
ive the same issue.

**Comment by ryanteck** [comment]
I've been using the version of the module I've forked on my web store and
haven't found issues. Think there's still a bug or two to iron out but for
the most part it has been working.



*Thanks -*

*Ryan Walmsley*
*Ryanteck LTD.*
*Email: *Ryanteck@gmail.com
*Skype:* Ryanteck
Website:* Http://ryanteck.org.uk <Http://ryanteck.org.uk>*

**Comment by NadjibBELLOUNDJA** [comment]
It works now.

Thanks for your help.

**Comment by trevorgilligan** [comment]
Hi there thanks for reply, it still doesn’t work

 

How do I get it to remove the paypal order summary.

 

It goes paypal -> prestashop order summary -> prestashop order confirmation

 

I would like paypal -> prestashop order confirmation.

 

Thank you, Trev

**Comment by franksmule** [comment]
Thanks @ryanteck
