### ISSUE TITLE
Error found in log when client create an order

### ISSUE THREAD

**Issue by bogdan-l** [franksmule/prestashop-stripejs#22]
Hi,

I have problems with clients when they pay their orders. They say they have a blank page.

So, I checked the log errors file and I found this : PHP Notice:  Undefined variable: result_json in /var/www/[my_presatshop_folder]/modules/stripejs/stripejs.php on line 547, referer: https://[domain.name]/commande?multi-shipping=

**Comment by franksmule** [comment]
Thanks @ryanteck
