### ISSUE TITLE
A couple of issues with 1.0.2-Beta and 0.9.9 on PS 1.5.6.2

### ISSUE THREAD

**Issue by Strikkhopp** [franksmule/prestashop-stripejs#23]
Once the order is confirmed I get this message:
UNFORTUNATELY WE DETECTED A PROBLEM WHILE PROCESSING YOUR ORDER AND IT NEEDS TO BE REVIEWED.
DO NOT TRY TO SUBMIT YOUR ORDER AGAIN, AS THE FUNDS HAVE ALREADY BEEN RECEIVED. WE WILL REVIEW THE ORDER AND PROVIDE A STATUS SHORTLY.
(YOUR ORDER'S REFERENCE: OAUPONMQC)

Downgraded the module to 0.9.9:
Same thing happens...

The card is charged:

Stripe Payment Details
Stripe Transaction ID: ch_15Z**********************

Status: Paid
Amount: 185,00 kr
Processed on: 2015-02-23 19:49:29
Credit card: (Exp.: 0/0)
Last 4 digits: 0000 (CVC Check: FAILED)
Processing Fee: 0,00 kr

Mode: Live

Any help appreciated.

Rgds,

Petter

**Comment by franksmule** [comment]
Thanks @ryanteck
