### ISSUE TITLE
»There was a problem with your payment«

### ISSUE THREAD

**Issue by jsphpl** [franksmule/prestashop-stripejs#7]
What am i doing wrong? Any hints?

I enabled test mode in both stripe and prestashop and entered the test credit card data shown in the screenshot. PS version 1.6.0.5

![bildschirmfoto von 2014-03-26 15 51 23](https://f.cloud.github.com/assets/5419165/2526073/59bdaf26-b4f6-11e3-9082-da894aaa4790.png)

**Comment by trevorgilligan** [comment]
hi @franksmule , i have this module thank you very much. i have similar issue, the 1st time i always get this problem "problem with card" and i do not see ajax-loader. the 2nd time it works and i get the ajax loader. why is ajax loader not working the 1st time? thank you
![ajax-loader](https://cloud.githubusercontent.com/assets/12951088/14232451/51519650-f9a4-11e5-8ec3-c1acf40e2690.gif)
