### ISSUE TITLE
Blank screen after successful checkout

### ISSUE THREAD

**Issue by jsphpl** [franksmule/prestashop-stripejs#8]
After successful payment, i get a blank screen. Test mode does not work at all, so i can't reproduce this issue too often (credit card fees). PS Version is 1.6.0.5.

![bildschirmfoto 2014-03-26 um 15 22 33](https://f.cloud.github.com/assets/5419165/2525984/532d26ba-b4f5-11e3-85d2-5c34cdea6b4f.png)

**Comment by bogdan-l** [comment]
Hi, I have the last version of your module but my clients always have blank page after they pay...
